// src/app/projects/survivor-stats/players/page.tsx
import PageHeader from "@/app/projects/survivor-stats/components/PageHeader";
import PlayersExplorerClient from "@/components/explorer/PlayersExplorerClient";

// These files are generated by: npm run build:explorer
import duels from "@/data/explorer/duels.v1.json";
import meta from "@/data/explorer/meta.v1.json";

export default function PlayersExplorerPage() {
  return (
    <>
      <PageHeader
        title="Players Explorer"
        subtitle="Use slicers to filter duel-level events. Sort the table by any metric."
      />

      <div className="mt-4">
        <PlayersExplorerClient duels={duels as any} meta={meta as any} />
      </div>
    </>
  );
}
